#
# Specific services to work with KNP Menu
#

parameters:

    flob_foundation.twig_extension.class: Flob\Bundle\FoundationBundle\Twig\MenuExtension

services:

    fbfb.twig_extension:
        class: %flob_foundation.twig_extension.class%
        arguments:
            - @knp_menu.helper
            - @twig
            - %flob_foundation.template.breadcrumb%
        tags:
            - { name: twig.extension }
