language: php

php:
    - 5.5
    - 5.6
    - 7
    - hhvm

sudo: false

env:
    matrix:
        - COMPOSER_PARAMETERS="--prefer-stable"
        - COMPOSER_PARAMETERS="--prefer-stable --prefer-lowest"

before_script:
    - composer self-update
    - composer $COMPOSER_PARAMETERS update

script:
    - ./vendor/bin/phpunit
